vich_uploader:
    db_driver: orm

    mappings:
        notices_images:
            uri_prefix:         '%app.path.notices_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.notices_images%'
        media_images:
            uri_prefix:         '%app.path.media_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.media_images%'
        software_images:
            uri_prefix:         '%app.path.software_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.software_images%'
        projects_images:
            uri_prefix:         '%app.path.projects_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.projects_images%'
        publication_files:
            uri_prefix:         '%app.path.publication_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.publication_files%'
        beetles_files:
            uri_prefix:         '%app.path.beetles_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.beetles_files%'
        cv:
            uri_prefix:         '%app.path.cv%'
            upload_destination: '%kernel.project_dir%/public%app.path.cv%'
